import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import { supabase } from '../../utils/supabaseClient'
import styles from '../../styles/Home.module.css'

export default function Auth() {
    const [loading, setLoading] = useState(false)
    const [email, setEmail] = useState('')

    const handleLogin = async (email) => {
        try {
            setLoading(true)
            const { error } = await supabase.auth.signIn({ email })
            if (error) throw error
            alert('Check your email for the login link!')
        } catch (error) {
            alert(error.error_description || error.message)
        } finally {
            setLoading(false)
        }
    }

    return (
        <>
            <Head>
                <title>Whip Music - Community</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.container}>
                <main>
                    <div className="container w-3/3 lg:w-2/3 bg-indigo-50">
                        <div className="p-10 h-screen row flex flex-center justify-center">
                            <div className="col-6 form-widget">
                                <h1 className="p-10 font-bold text-3xl">Welcome to the Whip Music Community</h1>
                                <p className="px-10 font-medium text-xl">Sign in via magic link with your email below</p>
                                <div className="mt-6 px-10 w-fit">
                                    <label htmlFor="email" className="block text-sm font-medium text-indigo-800">
                                        Email
                                    </label>
                                    <div className="mt-1 relative rounded-md shadow-sm">
                                        <input
                                            id={email}
                                            className="focus:ring-indigo-800 focus:border-indigo-800 block w-auto sm:w-auto pl-2 pr-12 sm:text-sm border-gray-300 rounded-md"
                                            type="email"
                                            placeholder="hello@whipmusic.com"
                                            value={email}
                                            onChange={(e) => setEmail(e.target.value)}
                                        />
                                    </div>
                                </div>
                                <div className="px-10">
                                    <button className="mt-6 justify-items-start bg-indigo-800 hover:bg-white hover:border-2 border-indigo-800  drop-shadow-md hover:drop-shadow-lg text-white hover:text-indigo-800 font-bold py-2 px-4 rounded inline-flex items-center"
                                        onClick={(e) => {
                                            e.preventDefault()
                                            handleLogin(email)
                                        }}
                                        disabled={loading}
                                    >
                                        <span>{loading ? 'Loading' : 'Send magic link'}</span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </main >
            </div>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                     Ian M. Deployed This Music Forum App on {' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span> 
                </a>
            </footer>

        </>

    )
}